<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-07-29 16:38

$extensionPath = t3lib_extMgm::extPath('fileman');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_fileman_controller_categorycontroller' => $extensionClassesPath . 'Controller/CategoryController.php',
	'tx_fileman_controller_categorycontrollertest' => $extensionPath . 'Tests/Unit/Controller/CategoryControllerTest.php',
	'tx_fileman_controller_filecontroller' => $extensionClassesPath . 'Controller/FileController.php',
	'tx_fileman_controller_filecontrollertest' => $extensionPath . 'Tests/Unit/Controller/FileControllerTest.php',
	'tx_fileman_controller_linkcontroller' => $extensionClassesPath . 'Controller/LinkController.php',
	'tx_fileman_domain_model_category' => $extensionClassesPath . 'Domain/Model/Category.php',
	'tx_fileman_domain_model_categorytest' => $extensionPath . 'Tests/Unit/Domain/Model/CategoryTest.php',
	'tx_fileman_domain_model_file' => $extensionClassesPath . 'Domain/Model/File.php',
	'tx_fileman_domain_model_filetest' => $extensionPath . 'Tests/Unit/Domain/Model/FileTest.php',
	'tx_fileman_domain_model_frontenduser' => $extensionClassesPath . 'Domain/Model/FrontendUser.php',
	'tx_fileman_domain_model_frontendusergroup' => $extensionClassesPath . 'Domain/Model/FrontendUserGroup.php',
	'tx_fileman_domain_model_link' => $extensionClassesPath . 'Domain/Model/Link.php',
	'tx_fileman_domain_repository_categoryrepository' => $extensionClassesPath . 'Domain/Repository/CategoryRepository.php',
	'tx_fileman_domain_repository_filerepository' => $extensionClassesPath . 'Domain/Repository/FileRepository.php',
	'tx_fileman_domain_repository_frontendusergrouprepository' => $extensionClassesPath . 'Domain/Repository/FrontendUserGroupRepository.php',
	'tx_fileman_domain_repository_frontenduserrepository' => $extensionClassesPath . 'Domain/Repository/FrontendUserRepository.php',
	'tx_fileman_domain_repository_linkrepository' => $extensionClassesPath . 'Domain/Repository/LinkRepository.php',
	'tx_fileman_domain_validator_fileurivalidator' => $extensionClassesPath . 'Domain/Validator/FileUriValidator.php',
	'tx_fileman_domain_validator_linksvalidator' => $extensionClassesPath . 'Domain/Validator/LinksValidator.php',
	'tx_fileman_domain_validator_linkurivalidator' => $extensionClassesPath . 'Domain/Validator/LinkUriValidator.php',
	'tx_fileman_mvc_controller_actioncontroller' => $extensionClassesPath . 'MVC/Controller/ActionController.php',
	'tx_fileman_mvc_controller_errorondebugcontroller' => $extensionClassesPath . 'MVC/Controller/ErrorOnDebugController.php',
	'tx_fileman_mvc_exception_nopersistrepository' => $extensionClassesPath . 'MVC/Exception/NoPersistRepository.php',
	'tx_fileman_persistence_nopersistrepository' => $extensionClassesPath . 'Persistence/NoPersistRepository.php',
	'tx_fileman_service_userservice' => $extensionClassesPath . 'Service/UserService.php',
	'tx_fileman_viewhelpers_format_camelcaseviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/CamelCaseViewHelper.php',
	'tx_fileman_viewhelpers_isemptyviewhelper' => $extensionClassesPath . 'ViewHelpers/IsEmptyViewHelper.php',
	'tx_fileman_viewhelpers_link_downloadviewhelper' => $extensionClassesPath . 'ViewHelpers/Link/DownloadViewHelper.php',
);
?>