<?php

########################################################################
# Extension Manager/Repository config file for ext: "fileman"
#
# Auto generated by Extension Builder 2012-03-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = [
	'title' => 'File Manager',
	'description' => 'File manager for category-based uploading, viewing and managing files on frontend. Includes complete management in backend.',
	'category' => 'plugin',
	'author' => 'Frenck Lutke',
	'author_email' => 'typo3@innologi.nl',
	'author_company' => 'www.innologi.nl',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '2.1.2',
	'constraints' => [
		'depends' => [
			'php' => '7.1',
			'typo3' => '8.7.0-9.5.99',
			'felogin' => '8.7.0'
		],
		'conflicts' => [],
		'suggests' => [],
	],
	'autoload' => [
		'psr-4' => [
			'Innologi\\Fileman\\' => 'Classes'
		]
	]
];
