<?php

########################################################################
# Extension Manager/Repository config file for ext: "fileman"
#
# Auto generated by Extension Builder 2012-03-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'File Manager',
	'description' => 'File manager for uploading, viewing and managing files on frontend. Includes complete management in backend.',
	'category' => 'plugin',
	'author' => 'Frenck Lutke',
	'author_email' => 'frenck@innologi.nl',
	'author_company' => 'www.innologi.nl',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 1,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
			'vhs' => '1.6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>